#!/usr/bin/env node
// Builds dist/contributions-card.js from src/contributions-card.js and the
// translations in translations/*.properties. No dependencies.
//
//   node scripts/build.mjs           build dist/
//   node scripts/build.mjs --check   fail if dist/ is out of date or a translation is invalid

import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, basename } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "src", "contributions-card.js");
const DIST = join(ROOT, "dist", "contributions-card.js");
const TRANSLATIONS_DIR = join(ROOT, "translations");
const REFERENCE = "en";
const MARKER = "/* @translations */ {}";
const PLURAL_FORMS = ["zero", "one", "two", "few", "many", "other"];

const errors = [];
const warnings = [];

/** Parses "key = value" lines. # and ! start comments; \n, \t, \\ and \uXXXX escapes are supported. */
function parseProperties(text, file) {
  const result = {};
  const lines = text.replace(/^﻿/, "").split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    let line = lines[i];
    // A trailing backslash continues the value on the next line.
    while (/(^|[^\\])(\\\\)*\\$/.test(line) && i + 1 < lines.length) {
      line = line.slice(0, -1) + lines[++i].replace(/^\s+/, "");
    }
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#") || trimmed.startsWith("!")) continue;
    const match = trimmed.match(/^([^=:\s]+)\s*[=:]\s*(.*)$/);
    if (!match) {
      errors.push(`${file}:${i + 1}: expected "key = value", got: ${trimmed}`);
      continue;
    }
    const [, key, raw] = match;
    if (key in result) errors.push(`${file}:${i + 1}: duplicate key "${key}"`);
    result[key] = raw.replace(/\\(u[0-9a-fA-F]{4}|.)/g, (_, c) =>
      c[0] === "u" && c.length === 5 ? String.fromCharCode(parseInt(c.slice(1), 16)) : { n: "\n", t: "\t" }[c] ?? c,
    );
  }
  return result;
}

const placeholders = (value) => [...value.matchAll(/\{(\w+)\}/g)].map((m) => m[1]).sort().join(",");

/** "days.one" -> "days"; other keys unchanged. */
function baseKey(key) {
  const last = key.split(".").pop();
  return PLURAL_FORMS.includes(last) ? key.slice(0, -(last.length + 1)) : key;
}

function loadTranslations() {
  const files = readdirSync(TRANSLATIONS_DIR).filter((f) => f.endsWith(".properties")).sort();
  const all = {};
  for (const file of files) {
    const lang = basename(file, ".properties");
    if (!/^[a-z]{2,3}(-[A-Za-z0-9]{2,8})*$/.test(lang)) {
      errors.push(`${file}: file name must be a language code, for example "de.properties" or "pt-BR.properties"`);
      continue;
    }
    all[lang] = parseProperties(readFileSync(join(TRANSLATIONS_DIR, file), "utf8"), `translations/${file}`);
  }
  if (!all[REFERENCE]) {
    errors.push(`translations/${REFERENCE}.properties is missing; it is the reference language`);
    return all;
  }

  const ref = all[REFERENCE];
  const refBases = new Map();
  for (const [key, value] of Object.entries(ref)) {
    const base = baseKey(key);
    if (!refBases.has(base)) refBases.set(base, placeholders(value));
  }
  for (const base of refBases.keys()) {
    const isPlural = Object.keys(ref).some((k) => k !== base && baseKey(k) === base);
    if (isPlural && !(`${base}.other` in ref)) errors.push(`${REFERENCE}.properties: plural "${base}" needs a "${base}.other" form`);
  }

  for (const [lang, table] of Object.entries(all)) {
    if (lang === REFERENCE) continue;
    const file = `translations/${lang}.properties`;
    const bases = new Set(Object.keys(table).map(baseKey));
    for (const [key, value] of Object.entries(table)) {
      const base = baseKey(key);
      if (!refBases.has(base)) {
        errors.push(`${file}: "${key}" is not in ${REFERENCE}.properties`);
      } else if (placeholders(value) !== refBases.get(base)) {
        errors.push(`${file}: "${key}" uses {${placeholders(value)}} but ${REFERENCE}.properties uses {${refBases.get(base)}}`);
      }
    }
    for (const base of refBases.keys()) {
      if (!bases.has(base)) warnings.push(`${file}: missing "${base}" (English is shown instead)`);
      const isPlural = Object.keys(ref).some((k) => k !== base && baseKey(k) === base);
      if (isPlural && bases.has(base) && !(`${base}.other` in table)) {
        errors.push(`${file}: plural "${base}" needs a "${base}.other" form`);
      }
    }
  }
  return all;
}

function build() {
  const translations = loadTranslations();
  const source = readFileSync(SRC, "utf8");
  if (source.split(MARKER).length !== 2) errors.push(`src/contributions-card.js must contain "${MARKER}" exactly once`);
  if (errors.length) return null;

  const bundled = JSON.stringify(translations, null, 2);
  const header =
    "// Generated by scripts/build.mjs from src/contributions-card.js and translations/*.properties.\n" +
    "// Do not edit this file directly.\n";
  return header + source.replace(MARKER, bundled);
}

const check = process.argv.includes("--check");
const output = build();
for (const w of warnings) console.warn(`warning: ${w}`);
if (!output) {
  for (const e of errors) console.error(`error: ${e}`);
  process.exit(1);
}
if (check) {
  if (!existsSync(DIST) || readFileSync(DIST, "utf8") !== output) {
    console.error("error: dist/contributions-card.js is out of date. Run `npm run build` and commit the result.");
    process.exit(1);
  }
  console.log("dist/contributions-card.js is up to date.");
} else {
  writeFileSync(DIST, output);
  console.log(`Built dist/contributions-card.js (${Object.keys(JSON.parse(output.match(/const TRANSLATIONS = ([\s\S]*?);\nconst FALLBACK/)[1])).join(", ")}).`);
}
